= WhereToGo.NSK Backend

Серверная часть приложения WhereToGo.NSK

== Общая информация

=== Основные сервисы

* Пользователи
* Места
* Категории
* Рекомендации

== Техническая информация

=== Технологический стек

* Java 17.0.8
* SpringBoot 2.7.5
* docker-compose 3.7
* Apache Maven 3.8.6

=== Используемый софт

* Intellij IDEA CE
* Android Studio
* Docker-desktop
* Postman
* pgAdmin Postgres

=== Сборка проекта

        mvn clean package

После сборки в папке /target появится файл с расширением *.jar, котороый можно запустить с помощью команды:

        java -jar /path/to/*.jar

=== Sonar

Для проверки тестового покрытия кода необходимо провести сборку проекта:

        mvn clean package

А затем вызвать sonar с помощью:

        mvn sonar:sonar

Также можно использовать комбинированную команду:

        mvn clean package sonar:sonar

=== Docker-контейнеры:

Предварительно необходимо настроить локально окружение для запуска докер контейнеров.
Необходимо установить docker на локальное ПО. Для windows систем можно установить Docker-desktop.

Необходимо сформировать два файла:

**db.properties**:

        spring.datasource.url=${POSTGRES_URL:jdbc:postgresql://localhost:5435/where2go}
        spring.datasource.username=${POSTGRES_USER:<username>}
        spring.datasource.password=${POSTGRES_PASSWORD:<password>}
        spring.datasource.driver-class-name=org.postgresql.Driver

**properties.env**:

        SPRING_DATASOURCE_URL=jdbc:postgresql://db/where2go
        SPRING_DATASOURCE_USERNAME=<username>
        SPRING_DATASOURCE_PASSWORD=<password>
        SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
        SPRING_DATA_JDBC_REPOSITORIES_ENABLED=false
        SPRING_JPA_SHOW_SQL=false
        SPRING_JPA_HIBERNATE_DDL_AUTO=validate
        SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQL9Dialect
        SERVER_PORT=8081

Оба файла необходимо поместить в директорию: _**where-to-go-back/src/main/resources/**_

Секреты для базы данных назначаются самостоятельно в зависимости от созданной БД, в случае локального запуска можно
взять секреты из [docker-compose.yml](docker/docker-compose.yml) файла.

Сборка контейнеров выполняется в два этапа:

==== Сборка проекта WhereToGo

        cd where-to-go-nsk/docker/ && docker-compose up -d

==== Сборка сервера OpenRouteService

        cd where-to-go-nsk/docker/ors/ && docker-compose up -d

Для сервиса openroute необходимо загрузить карту Сибирского федерального округа отсюда: http://download.geofabrik.de/russia/siberian-fed-district-latest.osm.pbf,
а затем поместить его в директорию **_where-to-go-nsk/docker/ors/resources_** (предварительно ее нужно создать).
После первичной настройки в файле **_docker/ors/docker/conf/ors-config.json_** необходимо найти директиву профилей
и внести туда еще один профиль помимо "car":

    "profiles": {
          "active": [
            "car", "walking"
          ],
        ...

==== Обновление контейнера приложения

Пересобрать контейнер при изменении *.jar файла приложения:

        docker-compose build app
        docker-compose up -d

=== Swagger-UI

Посмотреть документацию API: http://localhost:8081/swagger-ui/[Swagger-UI]