DROP VIEW IF EXISTS V_PLACES_INFO;

CREATE VIEW V_PLACES_INFO
AS
SELECT T_PLACE.*, CATEGORY_ID
FROM T_PLACE
         JOIN T_PLACE_CATEGORY PC ON T_PLACE.ID = PC.PLACE_ID
ORDER BY T_PLACE.ID;
COMMENT ON VIEW V_PLACES_INFO IS 'Содержит полную информацию о местах, в том числе их категории и подкатегории';

DROP TABLE IF EXISTS T_PLACE_SUBCATEGORY;
DROP TABLE IF EXISTS T_USER_COEFFICIENT_SUB;
DROP TABLE IF EXISTS T_USER_COEFFICIENT_MAIN;
DROP TABLE IF EXISTS T_SUBCATEGORY;

CREATE TABLE IF NOT EXISTS T_USER_COEFFICIENT
(
    CATEGORY_ID  INT8   NOT NULL,
    USER_ID      INT8   NOT NULL,
    COEFFICIENT  FLOAT8 NOT NULL,
    COUNT_PLACES INT8   NOT NULL,
    PRIMARY KEY (CATEGORY_ID, USER_ID)
);

--Глобальные категории
UPDATE T_CATEGORY
SET CATEGORY_PATH = 'В_ЧЕРТЕ_ГОРОДА'
WHERE NAME LIKE 'В ЧЕРТЕ ГОРОДА';

UPDATE T_CATEGORY
SET CATEGORY_PATH = 'В_ОБЛАСТИ'
WHERE NAME LIKE 'В ОБЛАСТИ';

UPDATE T_CATEGORY
SET CATEGORY_PATH = 'СООРУЖЕНИЯ'
WHERE NAME LIKE 'СООРУЖЕНИЯ';

UPDATE T_CATEGORY
SET CATEGORY_PATH = 'ПРИРОДА'
WHERE NAME LIKE 'ПРИРОДА';

--Подкатегории
UPDATE T_CATEGORY
SET CATEGORY_PATH = 'СООРУЖЕНИЯ.ЗАБРОШКИ'
WHERE NAME LIKE 'ЗАБРОШКИ';

UPDATE T_CATEGORY
SET CATEGORY_PATH = 'СООРУЖЕНИЯ.АРХИТЕКТУРА'
WHERE NAME LIKE 'АРХИТЕКТУРА';

UPDATE T_CATEGORY
SET CATEGORY_PATH = 'В_ЧЕРТЕ_ГОРОДА.НОЧЬЮ'
WHERE NAME LIKE 'НОЧЬЮ';

