ALTER TABLE IF EXISTS T_PLACE ADD COLUMN DURATION INT NOT NULL DEFAULT 90;

CREATE INDEX IF NOT EXISTS LATITUDE_INDEX ON T_PLACE USING BTREE(LATITUDE);
CREATE INDEX IF NOT EXISTS LONGITUDE_INDEX ON T_PLACE USING BTREE(LONGITUDE);
