UPDATE T_PLACE
SET DURATION = CREATE_RANDOM_DURATION()
WHERE ID = 28;

UPDATE T_PLACE
SET DURATION = CREATE_RANDOM_DURATION()
WHERE ID = 29;

UPDATE T_PLACE
SET DURATION = CREATE_RANDOM_DURATION()
WHERE ID = 30;

UPDATE T_PLACE
SET DURATION = CREATE_RANDOM_DURATION()
WHERE ID = 31;

UPDATE T_PLACE
SET DURATION = CREATE_RANDOM_DURATION()
WHERE ID = 32;

UPDATE T_PLACE
SET DURATION = CREATE_RANDOM_DURATION()
WHERE ID = 33;

UPDATE T_PLACE
SET DURATION = CREATE_RANDOM_DURATION()
WHERE ID = 34;

UPDATE T_PLACE
SET DURATION = CREATE_RANDOM_DURATION()
WHERE ID = 35;

UPDATE T_PLACE
SET DURATION = CREATE_RANDOM_DURATION()
WHERE ID = 36;

UPDATE T_PLACE
SET DURATION = CREATE_RANDOM_DURATION()
WHERE ID = 37;

UPDATE T_PLACE
SET DURATION = CREATE_RANDOM_DURATION()
WHERE ID = 38;

UPDATE T_PLACE
SET DURATION = CREATE_RANDOM_DURATION()
WHERE ID = 39;

UPDATE T_PLACE
SET DURATION = CREATE_RANDOM_DURATION()
WHERE ID = 40;

UPDATE T_PLACE
SET DURATION = CREATE_RANDOM_DURATION()
WHERE ID = 41;

UPDATE T_PLACE
SET DURATION = CREATE_RANDOM_DURATION()
WHERE ID = 42;

UPDATE T_PLACE
SET DURATION = CREATE_RANDOM_DURATION()
WHERE ID = 43;

UPDATE T_PLACE
SET DURATION = CREATE_RANDOM_DURATION()
WHERE ID = 44;

UPDATE T_PLACE
SET DURATION = CREATE_RANDOM_DURATION()
WHERE ID = 45;

UPDATE T_PLACE
SET DURATION = CREATE_RANDOM_DURATION()
WHERE ID = 46;

UPDATE T_PLACE
SET DURATION = CREATE_RANDOM_DURATION()
WHERE ID = 47;

UPDATE T_PLACE
SET DURATION = CREATE_RANDOM_DURATION()
WHERE ID = 48;

UPDATE T_PLACE
SET DURATION = CREATE_RANDOM_DURATION()
WHERE ID = 49;

UPDATE T_PLACE
SET DURATION = CREATE_RANDOM_DURATION()
WHERE ID = 50;

UPDATE T_PLACE
SET DURATION = CREATE_RANDOM_DURATION()
WHERE ID = 51;