INSERT INTO T_CATEGORY
VALUES (1, 'ЗАБРОШКИ');
INSERT INTO T_CATEGORY
VALUES (2, 'СООРУЖЕНИЯ');
INSERT INTO T_CATEGORY
VALUES (3, 'НОЧЬЮ');
INSERT INTO T_CATEGORY
VALUES (4, 'ПРИРОДА');
INSERT INTO T_CATEGORY
VALUES (5, 'АРХИТЕКТУРА');
INSERT INTO T_CATEGORY
VALUES (6, 'В ЧЕРТЕ ГОРОДА');
INSERT INTO T_CATEGORY
VALUES (7, 'В ОБЛАСТИ');

INSERT INTO T_PLACE_CATEGORY
VALUES (1, 2);
INSERT INTO T_PLACE_CATEGORY
VALUES (1, 4);
INSERT INTO T_PLACE_CATEGORY
VALUES (1, 6);

INSERT INTO T_PLACE_CATEGORY
VALUES (2, 2);
INSERT INTO T_PLACE_CATEGORY
VALUES (2, 4);
INSERT INTO T_PLACE_CATEGORY
VALUES (2, 7);

INSERT INTO T_PLACE_CATEGORY
VALUES (3, 2);
INSERT INTO T_PLACE_CATEGORY
VALUES (3, 4);
INSERT INTO T_PLACE_CATEGORY
VALUES (3, 7);
INSERT INTO T_PLACE_CATEGORY
VALUES (3, 5);

INSERT INTO T_PLACE_CATEGORY
VALUES (4, 2);
INSERT INTO T_PLACE_CATEGORY
VALUES (4, 3);
INSERT INTO T_PLACE_CATEGORY
VALUES (4, 6);

INSERT INTO T_PLACE_CATEGORY
VALUES (5, 2);
INSERT INTO T_PLACE_CATEGORY
VALUES (5, 5);
INSERT INTO T_PLACE_CATEGORY
VALUES (5, 7);

INSERT INTO T_PLACE_CATEGORY
VALUES (6, 2);
INSERT INTO T_PLACE_CATEGORY
VALUES (6, 6);

INSERT INTO T_PLACE_CATEGORY
VALUES (7, 2);
INSERT INTO T_PLACE_CATEGORY
VALUES (7, 6);

INSERT INTO T_PLACE_CATEGORY
VALUES (8, 2);
INSERT INTO T_PLACE_CATEGORY
VALUES (8, 6);

INSERT INTO T_PLACE_CATEGORY
VALUES (9, 2);
INSERT INTO T_PLACE_CATEGORY
VALUES (9, 7);

INSERT INTO T_PLACE_CATEGORY
VALUES (10, 2);
INSERT INTO T_PLACE_CATEGORY
VALUES (10, 6);

INSERT INTO T_PLACE_CATEGORY
VALUES (11, 5);
INSERT INTO T_PLACE_CATEGORY
VALUES (11, 6);

INSERT INTO T_PLACE_CATEGORY
VALUES (12, 4);
INSERT INTO T_PLACE_CATEGORY
VALUES (12, 7);

INSERT INTO T_PLACE_CATEGORY
VALUES (13, 4);
INSERT INTO T_PLACE_CATEGORY
VALUES (13, 7);

INSERT INTO T_PLACE_CATEGORY
VALUES (14, 2);
INSERT INTO T_PLACE_CATEGORY
VALUES (14, 6);

INSERT INTO T_PLACE_CATEGORY
VALUES (15, 2);
INSERT INTO T_PLACE_CATEGORY
VALUES (15, 4);
INSERT INTO T_PLACE_CATEGORY
VALUES (15, 6);

INSERT INTO T_PLACE_CATEGORY
VALUES (16, 1);
INSERT INTO T_PLACE_CATEGORY
VALUES (16, 2);
INSERT INTO T_PLACE_CATEGORY
VALUES (16, 4);
INSERT INTO T_PLACE_CATEGORY
VALUES (16, 6);

INSERT INTO T_PLACE_CATEGORY
VALUES (17, 3);
INSERT INTO T_PLACE_CATEGORY
VALUES (17, 2);
INSERT INTO T_PLACE_CATEGORY
VALUES (17, 6);

INSERT INTO T_PLACE_CATEGORY
VALUES (18, 5);
INSERT INTO T_PLACE_CATEGORY
VALUES (18, 6);

INSERT INTO T_PLACE_CATEGORY
VALUES (19, 3);
INSERT INTO T_PLACE_CATEGORY
VALUES (19, 6);

INSERT INTO T_PLACE_CATEGORY
VALUES (20, 5);
INSERT INTO T_PLACE_CATEGORY
VALUES (20, 6);

INSERT INTO T_PLACE_CATEGORY
VALUES (21, 5);
INSERT INTO T_PLACE_CATEGORY
VALUES (21, 6);

INSERT INTO T_PLACE_CATEGORY
VALUES (22, 4);
INSERT INTO T_PLACE_CATEGORY
VALUES (22, 6);
INSERT INTO T_PLACE_CATEGORY
VALUES (22, 2);

INSERT INTO T_PLACE_CATEGORY
VALUES (23, 5);
INSERT INTO T_PLACE_CATEGORY
VALUES (23, 6);

INSERT INTO T_PLACE_CATEGORY
VALUES (24, 1);
INSERT INTO T_PLACE_CATEGORY
VALUES (24, 2);
INSERT INTO T_PLACE_CATEGORY
VALUES (24, 6);

INSERT INTO T_PLACE_CATEGORY
VALUES (25, 4);
INSERT INTO T_PLACE_CATEGORY
VALUES (25, 6);

INSERT INTO T_PLACE_CATEGORY
VALUES (26, 5);
INSERT INTO T_PLACE_CATEGORY
VALUES (26, 6);

INSERT INTO T_PLACE_CATEGORY
VALUES (27, 1);
INSERT INTO T_PLACE_CATEGORY
VALUES (27, 6);