DROP VIEW IF EXISTS V_PLACES_INFO;

CREATE VIEW V_PLACES_INFO
AS
SELECT T_PLACE.*, CATEGORY_ID, SUBCATEGORY_ID
FROM T_PLACE
         JOIN T_PLACE_CATEGORY PC ON T_PLACE.ID = PC.PLACE_ID
         LEFT JOIN T_PLACE_SUBCATEGORY PSC ON T_PLACE.ID = PSC.PLACE_ID
ORDER BY T_PLACE.ID;

COMMENT ON VIEW V_PLACES_INFO IS 'Содержит полную информацию о местах, в том числе их категории и подкатегории';