server:
  port: 8081
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: false
  mvc:
    path_match:
      matching-strategy: ant_path_matcher
  config:
    import: ./db.properties
    activate:
      on-profile: prod
logging:
  level:
    ru:
      nsu:
        fit:
          wheretogo: DEBUG

ru:
  nsu:
    fit:
      wheretogo:
        ors:
          base_url: "http://ors-app:8080"
        genetic:
          max_population_size: 5
          max_generations_size: 15
          attraction_coefficient: 0.7
          duration_coefficient: 0.3