server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: false
  mvc:
    path_match:
      matching-strategy: ant_path_matcher
  config:
    import: file:local/db.properties