= WhereToGo.NSK Android

Мобильная часть приложения WhereToGo.NSK

== Общая информация

Основу приложения составляет окно карты, на которой располагаются маркеры - места.
Также включены окна авторизации, окна работы с фильтрами, списками избранных и посещенных мест.

== Техническая информация

=== Технологический стек

* Java 17.0.8
* Gradle 8.0.2

=== Сборка проекта

        ./gradlew app:build

=== Sonar

Для проверки тестового покрытия кода необходимо выполнить команду:

        ./gradlew sonarqube

=== Среда для запуска android-приложения

Для проверки работы приложения используется эмулятор Pixel 7 API 33, предоставляемый Device Manager-ом, встроенным в пакет программ Android Studio.
Создание эмулятора описано в https://developer.android.com/studio/run/managing-avds[инструкции]
с официального сайта https://developer.android.com/[developer.android.com]

После установки эмулятора, необзодимо запустить приложение через Android Studio - среда сама выполнит установку .apk файла на эмулятор и запустит приложение.