version: '3.7'

name: where-to-go-nsk
services:
  app:
    networks:
      - where-to-go-nsk
    image: 'where-to-go-nsk:1.0.0'
    build:
      context: ..
      dockerfile: /docker/Dockerfile
    container_name: where-to-go-nsk-app
    depends_on:
      - db
    ports:
      - "8081:8081"
    env_file:
      - ../src/main/resources/properties.env

  db:
    networks:
      - where-to-go-nsk
    container_name: where-to-go-postgres-db
    image: postgres:latest
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: where2go
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - database:/var/lib/postgresql/data
volumes:
  database:
networks:
  where-to-go-nsk:
    name: where-to-go-nsk
