version: '3.7'

name: where-to-go-nsk
services:
  app:
    image: 'where-to-go-nsk:release'
    build:
      context: ..
    container_name: where-to-go-nsk-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - ../src/main/resources/local/properties.env

  db:
    container_name: where-to-go-postgres-db
    image: postgres:latest
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: where2go
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres