version: '3.7'

services:
  db:
    container_name: where-to-go-postgres
    image: postgres:latest
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: where_to_go
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres