server:
  port: 8080
spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5435/where_to_go}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
  mvc:
    path match:
      matching-strategy: ant_path_matcher